name: kawanlama
description: Kawan Lama Test
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_route: ^7.8.0
  cupertino_icons: ^1.0.2
  drift: ^2.10.0
  flutter_easyloading: ^3.0.5
  get_it: ^7.6.0
  google_sign_in: ^6.1.6
  injectable: "2.1.2"
  intl: ^0.18.1
  intl_utils: ^2.8.3
  json_annotation: ^4.8.1
  path: ^1.8.3
  path_provider: ^2.0.15
  sqlite3_flutter_libs: ^0.5.15

  # firebase related
  firebase_core: ^2.24.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.5
  drift_dev: ^2.10.0
  flutter_lints: ^2.0.0
  injectable_generator: "2.1.6"
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_intl:
  generate: true
  enabled: true
  class_name: I10n
  arb_dir: lib/utilities/i10n
  output_dir: lib/utilities/i10n
