name: Build Apk

on:
  workflow_dispatch:
    inputs:
      flavor:
        description: 'Environment flavor'
        required: true
        type: choice
        options:
          - dev
          - staging
        default: 'staging'
      version:
        description: 'Build version'
        required: true
        default: '1.0.0'
      build-number:
        description: 'Build number'
        required: true
        default: '1'
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'jetbrains'
          java-version: '17'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install NDK
        run: |
          echo "y" | ${ANDROID_HOME}/cmdline-tools/16.0/bin/sdkmanager --install 'ndk;23.1.7779620'
      
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.1
      
      - name: Set short commit ID
        id: commit_id
        run: echo "COMMIT_ID=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
 
      - name: Install dependencies
        run: dart pub get

      - name: Build APK
        run: | 
          flutter build apk --release
