name: Build Apk

on:
  workflow_dispatch:
    inputs:
      flavor:
        description: 'Environment flavor'
        required: false
        type: choice
        options:
          - dev
          - staging
        default: 'staging'
      version:
        description: 'Build version'
        required: true
        default: '1.0.0'
      build-number:
        description: 'Build number'
        required: true
        default: '1'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set short commit ID
        id: commit_id
        run: echo "COMMIT_ID=$(git rev-parse --short HEAD)" >> $GITHUB_ENV  # Use $GITHUB_ENV for environment variables
 
      - name: Install dependencies
        run: flutter pub upgrade --major-versions  # Using Flutter's pub get instead of dart pub get

      - name: Build APK
        run: |
          flutter build apk --release --build-name ${{ github.event.inputs.version }} --build-number ${{ github.event.inputs.build-number }}
